# 1. Import Libraries and Load Dataset

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("../data/ai_human_text.csv")

df = pd.read_csv(DATA_PATH)

df.head()

                                                text  generated
0  Cars. Cars have been around since they became ...        0.0
1  Transportation is a large necessity in most co...        0.0
2  "America's love affair with it's vehicles seem...        0.0
3  How often do you ride in a car? Do you drive a...        0.0
4  Cars are a wonderful thing. They are perhaps o...        0.0

# 2. Inspect Dataset

In [2]:
df.shape

(487235, 2)

In [3]:
df.columns

Index(['text', 'generated'], dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487235 entries, 0 to 487234
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   text       487235 non-null  object
 1   generated  487235 non-null  float64
dtypes: float64(1), object(1)
memory usage: 7.4+ MB

In [5]:
df = df[["text", "generated"]].copy()

df["text"] = df["text"].astype(str)
df["generated"] = df["generated"].astype(int)

df.head()

                                                text  generated
0  Cars. Cars have been around since they became ...          0
1  Transportation is a large necessity in most co...          0
2  "America's love affair with it's vehicles seem...          0
3  How often do you ride in a car? Do you drive a...          0
4  Cars are a wonderful thing. They are perhaps o...          0

In [6]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

Missing values:
text         0
generated    0
dtype: int64

Duplicates:
0

# 3. Clean Dataset

In [7]:
df = df.dropna()
df = df.drop_duplicates()

df["text"] = df["text"].str.strip()

df = df[df["text"] != ""]

df.shape

(487231, 2)

In [8]:
df["text_length"] = df["text"].apply(len)

df["text_length"].describe()

count    487231.000000
mean       2267.986569
std         987.299796
min           1.000000
25%        1582.000000
50%        2101.000000
75%        2722.000000
max        9180.000000
Name: text_length, dtype: float64

In [9]:
df = df[df["text_length"] >= 50].copy()

df.shape

(487218, 3)

In [10]:
df["generated"].value_counts()

generated
0    305797
1    181421
Name: count, dtype: int64

In [11]:
df["generated"].value_counts(normalize=True) * 100

generated
0    62.763896
1    37.236104
Name: proportion, dtype: float64

# 4. Save Clean Dataset

In [13]:
from pathlib import Path

PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = PROCESSED_DIR / "ai_human_text_cleaned.parquet"

df.to_parquet(OUTPUT_FILE, index=False)

print(f"Saved cleaned dataset to: {OUTPUT_FILE}")

Saved cleaned dataset to: ..\data\processed\ai_human_text_cleaned.parquet